server:
  port: 8888
spring:
  application:
    name: shop
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.arino.pojo
  mapper-locations: classpath:mapper/*.xml